# Generated by Django 4.1.4 on 2022-12-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['updated_at', 'created_at']},
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.CharField(choices=[('en_EN', 'English'), ('sp_SP', 'Spanish'), ('tr_TR', 'Turkish'), ('ch_CH', 'Chinese'), ('ar_AR', 'Arabic'), ('fr_FR', 'French')], default='en_EN', max_length=5),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_channels', to='api.channel'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('genre', models.CharField(choices=[('history', 'History'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('action', 'Action'), ('horror', 'Horror'), ('drama', 'Drama'), ('other', 'Other')], default='history', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.channel')),
            ],
            options={
                'ordering': ['updated_at', 'created_at'],
            },
        ),
    ]
