# Generated by Django 4.1.4 on 2022-12-21 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_channel_channel_image_content_content_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_image',
            field=models.ImageField(default='/media/x.png', upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(default='/media/x.pdf', upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'pdf', 'txt'])]),
            preserve_default=False,
        ),
    ]
